Adding 0-transfer_file File

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,13 +1,26 @@
 #!/usr/bin/env bash
 
-if [ "$#" -ne 4 ]; then
-    echo "Usage: $(basename "$0") PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
+# Check if at least 4 parameters are provided
+if [ "$#" -lt 4 ]; then
+  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-file="$1"
-ip="$2"
-user="$3"
-key="$4"
+# Assign parameters to variables
+FILE_PATH="$1"
+SERVER_IP="$2"
+USERNAME="$3"
+SSH_KEY_PATH="$4"
 
-scp -i "$key" -o StrictHostKeyChecking=no "$file" "$user"@"$ip":~/ 
+# Disable strict host key checking for scp
+SCP_OPTIONS="-o StrictHostKeyChecking=no"
+
+# Use scp to transfer the file to the server's home directory
+scp $SCP_OPTIONS -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
+
+# Check if scp command was successful
+if [ "$?" -eq 0 ]; then
+  echo "File $FILE_PATH transferred successfully to $USERNAME@$SERVER_IP:~/"
+else
+  echo "Error: File transfer failed."
+fi
